# Este archivo de entrada no verifica todo el proyecto, de hecho es bastante básico.
# Pero si querían comprobar con algo como se vería post-minimos, pueden darse masomenos una idea.
# Los archivos de entrada reales van a ser más complejos.

mount -path="/tmp/discos calificacion/disco oficial.dk"  -name=p1 #001a
login -usr=root -pwd=123 -id=001a
mkgrp -name=prueba
mkgrp -name="a b c"
mkusr -usr=renato -pwd=1234567 -grp=root
chmod -path=/ -ugo=774
logout
login -usr=renato -pwd=1234567 -id=001a 
# Los comandos de aqui en adelante no deberian ser problema, porque renato pertenece al grupo root y los
# permisos del directorio raiz son 774.
touch -stdin -r -path=/usr/include/mysql/errmsg.h
touch -stdin -r -path=/usr/include/mysql/field_types.h
touch -stdin -r -path=/usr/include/mysql/my_command.h
touch -stdin -r -path=/usr/include/mysql/my_compress.h
touch -stdin -r -path=/usr/include/mysql/my_list.h
mkdir -p -path=/usr/include/mysql/mysql
touch -stdin -r -path=/usr/include/mysql/mysql/client_plugin.h
touch -stdin -r -path=/usr/include/mysql/mysql_com.h
touch -stdin -r -path=/usr/include/mysql/mysqld_error.h
touch -stdin -r -path=/usr/include/mysql/mysql.h
touch -stdin -r -path=/usr/include/mysql/mysql/plugin_auth_common.h
touch -stdin -r -path=/usr/include/mysql/mysql_time.h
touch -stdin -r -path=/usr/include/mysql/mysql/udf_registration_types.h
touch -stdin -r -path=/usr/include/mysql/mysql_version.h
touch -stdin -r -path=/usr/include/mysql/mysqlx_ername.h
touch -stdin -r -path=/usr/include/mysql/mysqlx_error.h
touch -stdin -r -path=/usr/include/mysql/mysqlx_version.h
mkdir -p -path=/usr/include/pgsql/internal
touch -stdin -r -path=/usr/include/pgsql/internal/c.h
mkdir -p -path=/usr/include/pgsql/internal/libpq
touch -stdin -r -path=/usr/include/pgsql/internal/libpq-int.h
touch -stdin -r -path=/usr/include/pgsql/internal/libpq/pqcomm.h
touch -stdin -r -path=/usr/include/pgsql/internal/port.h
touch -stdin -r -path=/usr/include/pgsql/internal/postgres_fe.h
touch -stdin -r -path=/usr/include/pgsql/internal/pqexpbuffer.h
mkdir -p -path=/usr/include/ffmpeg/libavcodec
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/ac3_parser.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/adts_parser.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/avcodec.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/avdct.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/avfft.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/d3d11va.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/dirac.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/dv_profile.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/dxva2.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/jni.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/mediacodec.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/qsv.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/vaapi.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/vdpau.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/version.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/videotoolbox.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/vorbis_parser.h
touch -stdin -r -path=/usr/include/ffmpeg/libavcodec/xvmc.h
mkdir -p -path=/usr/include/ffmpeg/libavdevice
touch -stdin -r -path=/usr/include/ffmpeg/libavdevice/avdevice.h
touch -stdin -r -path=/usr/include/ffmpeg/libavdevice/version.h
mkdir -p -path=/usr/include/ffmpeg/libavfilter
touch -stdin -r -path=/usr/include/ffmpeg/libavfilter/avfilter.h
touch -stdin -r -path=/usr/include/ffmpeg/libavfilter/buffersink.h
touch -stdin -r -path=/usr/include/ffmpeg/libavfilter/buffersrc.h
touch -stdin -r -path=/usr/include/ffmpeg/libavfilter/version.h
mkdir -p -path=/usr/include/ffmpeg/libavformat
touch -stdin -r -path=/usr/include/ffmpeg/libavformat/avformat.h
touch -stdin -r -path=/usr/include/ffmpeg/libavformat/avio.h
touch -stdin -r -path=/usr/include/ffmpeg/libavformat/version.h
mkdir -p -path=/usr/include/ffmpeg/libavresample
touch -stdin -r -path=/usr/include/ffmpeg/libavresample/avresample.h
touch -stdin -r -path=/usr/include/ffmpeg/libavresample/version.h
mkdir -p -path=/usr/include/ffmpeg/libavutil
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/adler32.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/aes_ctr.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/aes.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/attributes.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/audio_fifo.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/avassert.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/avconfig.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/avstring.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/avutil.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/base64.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/blowfish.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/bprint.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/bswap.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/buffer.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/camellia.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/cast5.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/channel_layout.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/common.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/cpu.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/crc.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/des.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/dict.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/display.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/downmix_info.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/encryption_info.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/error.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/eval.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/ffversion.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/fifo.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/file.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/frame.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/hash.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/hdr_dynamic_metadata.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/hmac.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/hwcontext_cuda.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/hwcontext_d3d11va.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/hwcontext_drm.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/hwcontext_dxva2.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/hwcontext.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/hwcontext_mediacodec.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/hwcontext_qsv.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/hwcontext_vaapi.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/hwcontext_vdpau.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/hwcontext_videotoolbox.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/imgutils.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/intfloat.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/intreadwrite.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/lfg.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/log.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/lzo.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/macros.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/mastering_display_metadata.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/mathematics.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/md5.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/mem.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/motion_vector.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/murmur3.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/opt.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/parseutils.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/pixdesc.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/pixelutils.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/pixfmt.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/random_seed.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/rational.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/rc4.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/replaygain.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/ripemd.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/samplefmt.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/sha512.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/sha.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/spherical.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/stereo3d.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/tea.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/threadmessage.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/timecode.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/time.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/timestamp.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/tree.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/twofish.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/tx.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/version.h
touch -stdin -r -path=/usr/include/ffmpeg/libavutil/xtea.h
mkdir -p -path=/usr/include/ffmpeg/libpostproc
touch -stdin -r -path=/usr/include/ffmpeg/libpostproc/postprocess.h
touch -stdin -r -path=/usr/include/ffmpeg/libpostproc/version.h
mkdir -p -path=/usr/include/ffmpeg/libswresample
touch -stdin -r -path=/usr/include/ffmpeg/libswresample/swresample.h
touch -stdin -r -path=/usr/include/ffmpeg/libswresample/version.h
mkdir -p -path=/usr/include/ffmpeg/libswscale
touch -stdin -r -path=/usr/include/ffmpeg/libswscale/swscale.h
touch -stdin -r -path=/usr/include/ffmpeg/libswscale/version.h
touch -stdin -r -path=/usr/include/R/Rconfig.h
touch -stdin -r -path=/usr/include/R/Rdefines.h
touch -stdin -r -path=/usr/include/R/Rembedded.h
mkdir -p -path=/usr/include/R/R_ext
touch -stdin -r -path=/usr/include/R/R_ext/Altrep.h
touch -stdin -r -path=/usr/include/R/R_ext/Applic.h
touch -stdin -r -path=/usr/include/R/R_ext/Arith.h
touch -stdin -r -path=/usr/include/R/R_ext/BLAS.h
touch -stdin -r -path=/usr/include/R/R_ext/Boolean.h
touch -stdin -r -path=/usr/include/R/R_ext/Callbacks.h
touch -stdin -r -path=/usr/include/R/R_ext/Complex.h
touch -stdin -r -path=/usr/include/R/R_ext/Connections.h
touch -stdin -r -path=/usr/include/R/R_ext/Constants.h
touch -stdin -r -path=/usr/include/R/R_ext/Error.h
touch -stdin -r -path=/usr/include/R/R_ext/eventloop.h
touch -stdin -r -path=/usr/include/R/R_ext/GetX11Image.h
touch -stdin -r -path=/usr/include/R/R_ext/GraphicsDevice.h
touch -stdin -r -path=/usr/include/R/R_ext/GraphicsEngine.h
touch -stdin -r -path=/usr/include/R/R_ext/Itermacros.h
touch -stdin -r -path=/usr/include/R/R_ext/Lapack.h
touch -stdin -r -path=/usr/include/R/R_ext/libextern.h
touch -stdin -r -path=/usr/include/R/R_ext/Linpack.h
touch -stdin -r -path=/usr/include/R/R_ext/MathThreads.h
touch -stdin -r -path=/usr/include/R/R_ext/Memory.h
touch -stdin -r -path=/usr/include/R/R_ext/Parse.h
touch -stdin -r -path=/usr/include/R/R_ext/Print.h
touch -stdin -r -path=/usr/include/R/R_ext/PrtUtil.h
touch -stdin -r -path=/usr/include/R/R_ext/QuartzDevice.h
touch -stdin -r -path=/usr/include/R/R_ext/Rallocators.h
touch -cont=/tmp/data/curl.h -path=/usr/include/R/R_ext/Random.h
touch -stdin -r -path=/usr/include/R/R_ext/Rdynload.h
touch -stdin -r -path=/usr/include/R/R_ext/R-ftp-http.h
touch -stdin -r -path=/usr/include/R/R_ext/Riconv.h
touch -stdin -r -path=/usr/include/R/R_ext/RS.h
touch -stdin -r -path=/usr/include/R/R_ext/RStartup.h
touch -stdin -r -path=/usr/include/R/R_ext/stats_package.h
touch -stdin -r -path=/usr/include/R/R_ext/stats_stubs.h
touch -stdin -r -path=/usr/include/R/R_ext/Utils.h
touch -stdin -r -path=/usr/include/R/R_ext/Visibility.h
touch -stdin -r -path=/usr/include/R/R.h
touch -stdin -r -path=/usr/include/R/Rinterface.h
touch -stdin -r -path=/usr/include/R/Rinternals.h
touch -stdin -r -path=/usr/include/R/Rmath.h
touch -stdin -r -path=/usr/include/R/Rversion.h
touch -stdin -r -path=/usr/include/R/S.h
rm -path=/usr/include/R/Parse.h
rm -path=/usr/include/mysql/my_compress.h
rm -path=/usr/include/ffmpeg/libavdevice
mkdir -path=/usr/include/X11
touch -size=889 -path=/usr/include/X11/Object.h
edit -stdin -path=/usr/include/X11/Object.h
ren -path=/usr/include/ffmpeg/libavutil/log.h -name=cambiado.h
logout
